### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by mithro** [PeterMonsson/sv_waveterm#11]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thanks!

**Comment by PeterMonsson** [comment]
Do you mean something like #12 ?

**Comment by mithro** [comment]
Yes, thanks!

(Although licensing under CC-BY-NC means I won't be able to use it.)

**Comment by PeterMonsson** [comment]
I use CC-BY-NC-SA to discourage commercial use, as the maturity just isn’t there yet.

I am an independent consultant, so having my name on half-baked stuff that people use for real work is bad for future contracts. 

On the other hand, working in public, releasing early and getting feedback from enthusiasts, early adopters, etc. will make this project more useful faster than having me work in a private repository. 

I am making a trade off with CC-BY-NC-SA now that I hope I won’t have to do forever

**Comment by mithro** [comment]
Your welcome to do whatever you think it best, you don't owe me anything. Good luck with your project!
